language: python

# Required for Python 3.7
dist: xenial 

# When adding a version here, remember to change it in setup.py
python:
    - "3.6"
    - "3.7"
    - "3.8"

install:
    - python setup.py --quiet install
    - pip --quiet install coverage python-coveralls

script:
    - python setup.py --quiet test

after_success:
    - coverage run --source makemock tests.py
    - coveralls
